[workspace]
resolver = "3"
members = ["crates/block-parse", "crates/block-parse-gui"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
block-parse = { path = "crates/block-parse" }
serde = { version = "1", features = ["derive"] }
ron = "0.12"
egui = "0.36"
eframe = "0.36"
clap = { version = "4", features = ["derive"] }
rfd = "0.17"
winit = "0.30"
palette = { version = "0.7", default-features = false, features = ["std"] }
